# Generated by Django 4.2.3 on 2023-10-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('day', models.CharField(choices=[('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wensday', 'Wensday'), ('thursday', 'Thursday'), ('friday', 'Friday')], default='saturday', max_length=200)),
                ('time', models.CharField(choices=[('9-10:30', '9-10:30'), ('10:30-12', '10:30-12'), ('13-15', '13-15'), ('15-17', '15-17'), ('17-19', '17-19')], default='9-10:30', max_length=200)),
            ],
        ),
    ]
