# Generated by Django 4.2.3 on 2023-10-01 18:59

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFF00', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
