# Generated by Django 4.2.3 on 2023-10-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly', '0002_object_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('saturday', 'Saturday'), ('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wensday', 'Wensday'), ('thursday', 'Thursday'), ('friday', 'Friday')], default='saturday', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('9-10:30', '9-10:30'), ('10:30-12', '10:30-12'), ('13-15', '13-15'), ('15-17', '15-17'), ('17-19', '17-19')], default='9-10:30', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='object',
            name='day',
        ),
        migrations.RemoveField(
            model_name='object',
            name='time',
        ),
        migrations.AddField(
            model_name='object',
            name='day',
            field=models.ManyToManyField(to='weekly.day'),
        ),
        migrations.AddField(
            model_name='object',
            name='time',
            field=models.ManyToManyField(to='weekly.time'),
        ),
    ]
